### ISSUE TITLE
dropwizard fails with jdk9

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#118]
bug in validator https://issues.jboss.org/browse/WFLY-6043

root@gluu:/opt/oxd-https-extension/lib# sudo java -jar oxd-https-extension-3.1.1.Final.jar server oxd-https.yml
SLF4J: Detected both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path, preempting StackOverflowError. 
SLF4J: See also http://www.slf4j.org/codes.html#log4jDelegationLoop for more details.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
 at org.hibernate.validator.internal.util.Version.getJavaRelease(Version.java:36)
 at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:120)
 at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:106)
 at org.hibernate.validator.HibernateValidator.createSpecializedConfiguration(HibernateValidator.java:27)
 at org.hibernate.validator.HibernateValidator.createSpecializedConfiguration(HibernateValidator.java:24)
 at javax.validation.Validation$ProviderSpecificBootstrapImpl.configure(Validation.java:220)
 at io.dropwizard.validation.BaseValidator.newConfiguration(BaseValidator.java:28)
 at io.dropwizard.jersey.validation.Validators.newConfiguration(Validators.java:35)
 at io.dropwizard.jersey.validation.Validators.newValidatorFactory(Validators.java:27)
 at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:68)
 at io.dropwizard.Application.run(Application.java:72)
 at org.gluu.oxd.OxdHttpsApplication.main(OxdHttpsApplication.java:14)

**Comment by yuriyz** [comment]
@adrianbob since oxd 4.0.beta I've upgraded dropwizard to 1.3.1. Please check whether we still have problem with jdk9 after upgrade.

**Comment by yuriyz** [comment]
fixed during dropwizard upgrade to 1.3.1 version.
