### ISSUE TITLE
Permission ticket registration fails

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#132]
2017-12-19 16:22:23,972 DEBUG [org.xdi.oxd.server.service.UmaTokenService] PAT from site configuration, PAT: 797c1ab3-7646-45d8-882a-ffa9f5efaff3
2017-12-19 16:22:24,247 ERROR [org.xdi.oxd.rs.protect.resteasy.RptPreProcessInterceptor] Failed to register permission ticket.
org.jboss.resteasy.client.ClientResponseFailure: RESTEASY003150: Error status 400 Bad Request returned
	at org.jboss.resteasy.client.core.BaseClientResponse.createResponseFailure(BaseClientResponse.java:581)
	at org.jboss.resteasy.client.core.BaseClientResponse.createResponseFailure(BaseClientResponse.java:572)
	at org.jboss.resteasy.client.core.BaseClientResponse.checkFailureStatus(BaseClientResponse.java:566)
	at org.jboss.resteasy.client.core.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:39)
	at org.jboss.resteasy.client.core.ClientInvoker.invoke(ClientInvoker.java:128)
	at org.jboss.resteasy.client.core.ClientProxy.invoke(ClientProxy.java:89)
	at com.sun.proxy.$Proxy45.registerPermission(Unknown Source)
	at org.xdi.oxd.rs.protect.resteasy.RptPreProcessInterceptor.registerTicketResponse(RptPreProcessInterceptor.java:179)
	at org.xdi.oxd.server.op.RsCheckAccessOperation.execute(RsCheckAccessOperation.java:117)
	at org.xdi.oxd.server.op.RsCheckAccessOperation.execute(RsCheckAccessOperation.java:34)
	at org.xdi.oxd.server.Processor.process(Processor.java:76)
	at org.xdi.oxd.server.Processor.process(Processor.java:51)
	at org.xdi.oxd.server.SocketProcessor.run(SocketProcessor.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-19 16:22:24,248 ERROR [org.xdi.oxd.server.Processor] 
java.lang.NullPointerException
	at org.xdi.oxd.server.op.RsCheckAccessOperation.execute(RsCheckAccessOperation.java:121)
	at org.xdi.oxd.server.op.RsCheckAccessOperation.execute(RsCheckAccessOperation.java:34)
	at org.xdi.oxd.server.Processor.process(Processor.java:76)
	at org.xdi.oxd.server.Processor.process(Processor.java:51)
	at org.xdi.oxd.server.SocketProcessor.run(SocketProcessor.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by yuriyz** [comment]
Issue is not reproducible, it is shown by this build https://ox.gluu.org/jenkins/job/oxd/585/consoleFull

```
2017-12-20 06:32:04,332 DEBUG [org.xdi.oxd.rs.protect.resteasy.RptPreProcessInterceptor] Ticket registered, UMA realm="rs",as_uri="https://ce-dev4.gluu.org",error="insufficient_scope",ticket="7e76272b-9673-489e-8159-3af70724db69"
```
