### ISSUE TITLE
oxd 3.1.2 is compatible only with oxauth 3.1.2 and later. Need workaround for it and make it compatible with earlier version.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#145]
oxd 3.1.2 is compatible only with oxauth 3.1.2 and later because introspection format was changed. Need workaround for it and make it compatible with earlier version.
https://github.com/GluuFederation/oxauth/issues/696

**Comment by yuriyz** [comment]
2018-01-26 13:42:29,812 ERROR [org.xdi.oxd.server.Processor] org.codehaus.jackson.JsonParseException: Numeric value (1516954649585) out of range of int
 at [Source: org.jboss.resteasy.client.core.BaseClientResponse$InputStreamWrapper@2a531c8a; line: 1, column: 169]
org.jboss.resteasy.spi.ReaderException: org.codehaus.jackson.JsonParseException: Numeric value (1516954649585) out of range of int
 at [Source: org.jboss.resteasy.client.core.BaseClientResponse$InputStreamWrapper@2a531c8a; line: 1, column: 169]
    at org.jboss.resteasy.client.core.BaseClientResponse.readFrom(BaseClientResponse.java:477)
    at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:390)
    at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:361)
    at org.jboss.resteasy.client.core.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:64)
    at org.jboss.resteasy.client.core.ClientInvoker.invoke(ClientInvoker.java:128)
    at org.jboss.resteasy.client.core.ClientProxy.invoke(ClientProxy.java:89)
    at com.sun.proxy.$Proxy48.introspectToken(Unknown Source)
    at org.xdi.oxd.server.service.ValidationService.introspect(ValidationService.java:143)
    at org.xdi.oxd.server.service.ValidationService.validate(ValidationService.java:109)
    at org.xdi.oxd.server.service.ValidationService.validate(ValidationService.java:52)
    at org.xdi.oxd.server.Processor.process(Processor.java:74)
    at org.xdi.oxd.server.Processor.process(Processor.java:51)
    at org.xdi.oxd.server.SocketProcessor.run(SocketProcessor.java:55)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.jackson.JsonParseException: Numeric value (1516954649585) out of range of int
 at [Source: org.jboss.resteasy.client.core.BaseClientResponse$InputStreamWrapper@2a531c8a; line: 1, column: 169]
    at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
    at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
    at org.codehaus.jackson.impl.JsonParserBase.convertNumberToInt(JsonParserBase.java:829)
    at org.codehaus.jackson.impl.JsonParserBase.getIntValue(JsonParserBase.java:625)
    at org.codehaus.jackson.map.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:303)
    at org.codehaus.jackson.map.deser.std.StdDeserializer$IntegerDeserializer.deserialize(StdDeserializer.java:819)
    at org.codehaus.jackson.map.deser.std.StdDeserializer$IntegerDeserializer.deserialize(StdDeserializer.java:806)
    at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
    at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414)
    at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
    at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
    at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2704)
    at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1315)
    at org.codehaus.jackson.jaxrs.JacksonJsonProvider.readFrom(JacksonJsonProvider.java:419)
    at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:66)
    at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:56)
    at org.jboss.resteasy.client.core.BaseClientResponse.readFrom(BaseClientResponse.java:442)
    ... 15 more
2018-01-26 13:42:29,854 TRACE [org.xdi.oxd.server.Processor] Send back response: {"status":"error","data":{"error":"internal_error","details":null,"error_description":"Unknown internal server error occurs."}}

**Comment by yuriyz** [comment]
fixed
