### ISSUE TITLE
Client gets deleted from oxd-server after update_site command 

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxd#180]
oxd-server 3.1.3

Steps to reproduce:

1- Setup a client
2- Update the client without passing value for client_secret_expires_at

Update_site command sends value 0 for client_secret_expires_at when nothing is supplied. oxd-server considers this client as expired client and deletes from database.
This is throwing 

`ErrorResponseException{errorResponseCode=ErrorResponseCode{value='expired_client', description='Invalid oxd_id. Client is expired.'}}
        at org.xdi.oxd.server.service.RpService.checkClientExpiredWithException(RpService.java:73)
        at org.xdi.oxd.server.service.RpService.getRp(RpService.java:67)
        at org.xdi.oxd.server.service.ValidationService.validate(ValidationService.java:59)
        at org.xdi.oxd.server.Processor.process(Processor.java:74)
        at org.xdi.oxd.server.Processor.process(Processor.java:51)
        at org.xdi.oxd.server.SocketProcessor.run(SocketProcessor.java:55)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
2018-05-11 16:07:27,832 TRACE [org.xdi.oxd.server.Processor] Send back response: {"status":"error","data":{"error":"expired_client","details":null,"error_description":"Invalid oxd_id. Client is expired."}}`

Attached the log file.

[oxd-server.log](https://github.com/GluuFederation/oxd/files/1995000/oxd-server.log)

**Comment by yuriyz** [comment]
Fixed in 3.1.4 and master.
