### ISSUE TITLE
oxd throwing UMA-related error when working with OP that does not support UMA

### ISSUE THREAD

**Issue by bhammond604** [GluuFederation/oxd#207]
While using ORPCPY (https://github.com/bhammond604/oxd-rp-certification-python) to test oxd 3.1.3 against OpenIDs certification testing tool, OIDCTEST (https://github.com/rohe/oidctest), oxd keeps raising an error message stating that it is unable to retrieve `/.well-known/uma2-configuration`, even though OIDCTEST does not support UMA. oxd should be able to handle situations where UMA is not used or supported. 

Here is the error being raised by oxd through ORPCPY:
```127.0.0.1 - - [11/Jul/2018 11:55:34] "POST /test_1/ HTTP/1.1" 302 -
[2018-07-11 11:55:34,442] ERROR in app: Exception on /authorize/ [GET]
Traceback (most recent call last):
  File "/home/brandon/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/brandon/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/brandon/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/brandon/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/brandon/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/brandon/Projects/Work/oxd-rp-certification-python/oxd-rp-certification-python/core/flask_server.py", line 49, in authorize
    oxd_client.register_site()
  File "/home/brandon/.local/lib/python2.7/site-packages/oxdpython/client.py", line 110, in register_site
    raise OxdServerError(response['data'])
OxdServerError: oxd Server Error: no_uma_discovery_response
 Unable to fetch UMA discovery response /.well-known/uma2-configuration
127.0.0.1 - - [11/Jul/2018 11:55:34] "GET /authorize/ HTTP/1.1" 500 -
```

**Comment by yuriyz** [comment]
@bhammond604 please attach oxd-server.log file, so it's clear under what circumstances error occurs.

**Comment by yuriyz** [comment]
@bhammond604 also as far as I can see UMA Discovery fetched only if UMA related commands are executed (like resource registration or RPT request). Make sure you have `uma2_auto_register_claims_gathering_endpoint_as_redirect_uri_of_client` set to false in `oxd-conf.json`. I assume you have it set to `true` value. Otherwise if it is set to `false` and you don't call any UMA related commands, UMA Discovery should not be called.

**Comment by willow9886** [comment]
@yuriyz should this config value be set to `false` by default?

**Comment by yuriyz** [comment]
Idea was to keep default value true, so we do not get questions why redirect to Claims Gathering Endpoint fails. Probably better to add note to FAQ that if UMA is not available than need to set it to false?

**Comment by yuriyz** [comment]
added note to FAQ of 3.1.3, 3.1.3.1, 3.1.4 and 4.0.0

**Comment by bhammond604** [comment]
Could you please make the error message more explicit so that the end user is able to identify that the issue is in the configuration more quickly?

**Comment by yuriyz** [comment]
What exactly error message would you like to see?
