### ISSUE TITLE
unknown problem 

### ISSUE THREAD

**Issue by dollar007** [GluuFederation/oxd#23]
@yuriyz see attached file, gluu-server-2.4.2 and oxd-server-2.4.2
[oxd-server.txt](https://github.com/GluuFederation/oxd/files/161739/oxd-server.txt)

**Comment by yuriyz** [comment]
@dollar007 from log I can see that ssl error occured
```
2016-03-07 11:42:15,432 TRACE [org.xdi.oxd.server.service.HttpService] Created TRUST_ALL client.
2016-03-07 11:42:15,904 ERROR [org.xdi.oxauth.client.OpenIdConfigurationClient] peer not authenticated
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:421)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:126)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
```
To be honest I wonder why does it occurs if "trust_all_certs" is set to true. For some reason ssl validation fails.
There are two ways to proceed:
1. provide trusstore with imported certificate and put path to your trust store in oxd-conf.json
```
"trust_store_path":"<path to trust store>"
```
2. import certificate into java store
http://stackoverflow.com/questions/4325263/how-to-import-a-cer-certificate-into-a-java-keystore
