### ISSUE TITLE
ValueError in output from 3.1.4-4.0beta upgrade

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#276]
I followed the instructions given by @mbaser:

> Test procedure:
> 
>     1. install pip:
>     curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
>     python get-pip.py
>     2. install pyyaml:
>     pip install pyyaml
>     3. get upgrader:
>     wget  https://raw.githubusercontent.com/GluuFederation/oxd/version_4.0.beta/upgrade/oxd_updater.py
>     4. run upgrader:
>     python oxd_updater.py

**and at the end of the upgrade, there was a ValueError in the console:**

```
2018-11-28 00:19:19 (45.2 MB/s) - “oxd-server.yml.temp” saved [2898/2898]

Traceback (most recent call last):
  File "oxd_updater.py", line 267, in <module>
    oxd_default_site_config_json = json_load_byteified(oxd_default_site_config_json_back_fn)
  File "oxd_updater.py", line 136, in json_load_byteified
    json.load(open(file_handle), object_hook=_byteify),
  File "/usr/lib64/python2.6/json/__init__.py", line 267, in load
    parse_constant=parse_constant, **kw)
  File "/usr/lib64/python2.6/json/__init__.py", line 318, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 336, in raw_decode
    obj, end = self._scanner.iterscan(s, **kw).next()
  File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib64/python2.6/json/decoder.py", line 185, in JSONObject
    raise ValueError(errmsg("Expecting object", s, end))
ValueError: Expecting object: line 2 column 15 (char 16)
```

**Comment by mbaser** [comment]
New version is tested on CentOS7, this issue does not exist. Closing.
