### ISSUE TITLE
oxd: Getting Forbidden : 403 while using lsox script

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxd#329]
Steps to reproduce issue:

1. In a fresh installation **with running oxd**, go to /opt/oxd-server/bin
2. Enter
 sh lsox.sh -l 969545f5-ac6a-4e89-a7a6-9965883fa0f1 -a e43b4f6c-eb14-41b1-9552-ec97bd664878 (correct arguments)
3. Press Enter

**Expected**: The terminal should display the list of oxd_id and client_name
**Actual**: The terminal displays _Forbidden : 403. Failed to execute command against oxd-server on port Pair{first=8443, second=true}. Please check oxd_id or access_token really exists and is not malformed, error: HTTP 403 Forbidden_

javax.ws.rs.ForbiddenException: HTTP 403 Forbidden
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:221)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:193)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:467)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.method(ClientInvocationBuilder.java:313)
        at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:343)
        at com.sun.proxy.$Proxy51.getRp(Unknown Source)
        at org.gluu.oxd.server.Cli.tryToConnectToRunningOxd(Cli.java:211)
        at org.gluu.oxd.server.Cli.main(Cli.java:114)

We get same error for `-oxd_id` and `-d` commands.

**Comment by duttarnab** [comment]
**Findings:**
In past release we have added `token` variable to `org.gluu.oxd.common.params.GetRpParams` so `/get-rp` operation undergoes token validation in `org.gluu.oxd.server.RestResource.validateAccessToken`. When we are using lsox script we are not adding perfix 'Bearer ' with the access token so it fails everytime. This issue is only for lsox scripts (`org.gluu.oxd.server.Cli.java`) hence we are adding  'Bearer '  prefix  to the access_token before validation.

**Comment by yuriyz** [comment]
Fixed by https://github.com/GluuFederation/oxd/pull/330
