### ISSUE TITLE
Do not use PAT to request introspection (avoid exception related to missed `uma_protection` )

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#347]
ERROR  [18:54:17.498] [dw-19 - POST /get-authorization-url] o.g.o.s.s.UmaTokenService -  oxd requested scope PROTECTION but AS returned access_token without that scope, token scopes :openid 
ERROR  [18:54:17.498] [dw-19 - POST /get-authorization-url] o.g.o.s.s.UmaTokenService -  Please check AS(oxauth) configuration and make sure UMA scope (uma_protection) is enabled. 
TRACE  [18:54:17.504] [dw-19 - POST /get-authorization-url] o.g.o.s.s.IntrospectionService -  Exception during access token introspection. 
java.lang.RuntimeException: oxd requested scope PROTECTION but AS returned access_token without that scope, token scopes :openid
	at org.gluu.oxd.server.service.UmaTokenService.obtainTokenWithClientCredentials(UmaTokenService.java:193)
	at org.gluu.oxd.server.service.UmaTokenService.obtainToken(UmaTokenService.java:166)
	at org.gluu.oxd.server.service.UmaTokenService.obtainPat(UmaTokenService.java:148)
	at org.gluu.oxd.server.service.UmaTokenService.getPat(UmaTokenService.java:143)
	at org.gluu.oxd.server.service.IntrospectionService.introspectToken(IntrospectionService.java:44)
	at org.gluu.oxd.server.service.IntrospectionService.introspectToken(IntrospectionService.java:36)
	at org.gluu.oxd.server.service.ValidationService.introspect(ValidationService.java:145)
	at org.gluu.oxd.server.service.ValidationService.validate(ValidationService.java:118)
	at org.gluu.oxd.server.service.ValidationService.validate(ValidationService.java:51)
	at org.gluu.oxd.server.Processor.process(Processor.java:45)
	at org.gluu.oxd.server.RestResource.getObjectForJsonConversion(RestResource.java:234)
	at org.gluu.oxd.server.RestResource.process(RestResource.java:220)
	at org.gluu.oxd.server.RestResource.getAuthorizationUrl(RestResource.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by yuriyz** [comment]
Fixed by https://github.com/GluuFederation/oxd/commit/9950236e056280544d9ecc5b6ad7dd88a1537a75
