### ISSUE TITLE
Performance : oxd under high load has problem with `state` validation.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#372]
Under high load oxd shows 5% of error. The root cause is in thread safety of state validation. oxd should have 0% errors under high load.

![image](https://user-images.githubusercontent.com/2013070/65779554-a564f100-e150-11e9-8720-debaad8f4cc5.png)

```
**ERROR [2019-09-27 14:54:17,991] org.gluu.oxd.server.Processor: HTTP 400 Bad Request
! org.gluu.oxd.server.HttpException: HTTP 400 Bad Request
! at org.gluu.oxd.server.op.GetTokensByCodeOperation.validate(GetTokensByCodeOperation.java:110)
! at org.gluu.oxd.server.op.GetTokensByCodeOperation.execute(GetTokensByCodeOperation.java:40)
! at org.gluu.oxd.server.op.GetTokensByCodeOperation.execute(GetTokensByCodeOperation.java:25)
! at org.gluu.oxd.server.Processor.process(Processor.java:47)
! at org.gluu.oxd.server.RestResource.getObjectForJsonConversion(RestResource.java:234)
! at org.gluu.oxd.server.RestResource.process(RestResource.java:220)
! at org.gluu.oxd.server.RestResource.getTokenByCode(RestResource.java:103)
! at sun.reflect.GeneratedMethodAccessor259.invoke(Unknown Source)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)**
```

**Comment by duttarnab** [comment]
My system configuration allowed me to test with 15,000 threads with ramp-up time of 10 minutes.

**Comment by yuriyz** [comment]
@duttarnab we've moved `state` to persistence (from in-memory) for HA. Maybe it effects result. With is the error rate in case of 10000 executions ?

**Comment by duttarnab** [comment]
@yuriyz,  For 10,000 threads if we give ramp-up time of 400 secs then success rate is 100%.

For 10,000 threads if ramp-up time 1 sec then success rate 25%. It fails at `/register-site` with below error which tell client is not able to make 10,000 connections to oxd in 1 sec. We have tried increasing `maxThreads: 20000` and `maxQueuedRequests: 10000` in `oxd-server.yml` but still we are getting below error.

So I think instead of firing all 10,000 threads at a time we should provide some ramp-up time.

```
org.apache.http.conn.HttpHostConnectException: Connect to localhost:8443 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl$JMeterDefaultHttpClientConnectionOperator.connect(HTTPHC4Impl.java:336)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:843)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:574)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:67)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1231)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1220)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 19 more

```

**Comment by yuriyz** [comment]
10000 threads with 100% success is good result. Closing this ticket since state validation problem is fixed.
