### ISSUE TITLE
Upgrade `Dropwizard` dependency from version `1.3.1` to `2.0.0` in oxd

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxd#396]
Due to the upgrade of  `jackson` dependency version to `2.10.1` in `gluu-core-bom` project we are getting error in running oxd test.

```
WARN  [2019-12-21 15:58:57,223] org.jboss.resteasy.resteasy_jaxrs.i18n: RESTEASY002145: NoClassDefFoundError: Unable to load builtin provider org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider from jar:file:/C:/Users/ABC/.m2/repository/org/jboss/resteasy/resteasy-jackson2-provider/3.9.3.Final/resteasy-jackson2-provider-3.9.3.Final.jar!/META-INF/services/javax.ws.rs.ext.Providers
! java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.jsontype.PolymorphicTypeValidator
! at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
! ... 47 common frames omitted
! Causing: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/jsontype/PolymorphicTypeValidator
! at java.lang.Class.getDeclaredConstructors0(Native Method)
! at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
! at java.lang.Class.getConstructors(Class.java:1651)
! at org.jboss.resteasy.util.PickConstructor.pickSingletonConstructor(PickConstructor.java:30)
! at org.jboss.resteasy.spi.ResteasyProviderFactory.createConstructorInjector(ResteasyProviderFactory.java:2790)
! at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2782)
! at org.jboss.resteasy.spi.ResteasyProviderFactory.addMessageBodyReader(ResteasyProviderFactory.java:1017)
! at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1790)
! at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1718)
! at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:133)
! at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:45)
! at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.getProviderFactory(ResteasyClientBuilder.java:412)
! at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.build(ResteasyClientBuilder.java:454)
! at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.build(ResteasyClientBuilder.java:41)
! at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:114)
! at org.gluu.oxd.client.OxdClient.newClient(OxdClient.java:22)
! at org.gluu.oxd.server.Tester.newClient(Tester.java:32)
! at org.gluu.oxd.server.SetUpTest.beforeSuite(SetUpTest.java:47)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
! at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
! at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
! at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
! at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
! at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
! at org.testng.SuiteRunner.run(SuiteRunner.java:364)
! at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
! at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
! at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
! at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
! at org.testng.TestNG.runSuites(TestNG.java:1049)
! at org.testng.TestNG.run(TestNG.java:1017)
! at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
! at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
```

This error is due to version conflict in `jackson` library. The `dropwizard` (version: 1.3.1) 
uses `jackson` of version `2.9.5` and this is a transitive dependency in oxd which conflicts with `jackson-2.10.1` (from `gluu-core-bom`) during execution of test cases.

The cleanest solution here is using latest version of `dropwizard`  i.e. `2.0.0` in oxd which uses `jackson-2.10.1`.

**Comment by duttarnab** [comment]
Done using https://github.com/GluuFederation/oxd/pull/397
