### ISSUE TITLE
Set default `sync_client_from_op` and `sync_client_period_in_seconds` n RP for clients created using oxd version <= 4.1

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxd#471]
Steps to reproduce:

1. Register client using oxd version < 4.2.
2. Upgrade oxd to 4.2
2. Now execute `/get-authorization-url`. It should throw below error.

```
ERROR  [07:21:09.736] [dw-24 - POST /get-authorization-url] i.d.j.e.LoggingExceptionMapper -  Error handling a request: 618809bfdabd7100 
java.lang.NullPointerException: null
	at org.gluu.oxd.server.service.RpSyncService.shouldSync(RpSyncService.java:32)
	at org.gluu.oxd.server.service.RpSyncService.getRp(RpSyncService.java:46)
	at org.gluu.oxd.server.service.ValidationService.validateAccessToken(ValidationService.java:131)
	at org.gluu.oxd.server.RestResource.validateAccessToken(RestResource.java:315)
	at org.gluu.oxd.server.RestResource.getObjectForJsonConversion(RestResource.java:258)
	at org.gluu.oxd.server.RestResource.process(RestResource.java:242)
	at org.gluu.oxd.server.RestResource.getAuthorizationUrl(RestResource.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
...
```

**Comment by duttarnab** [comment]
Done in 4.2
