### ISSUE TITLE
Not acceptable error during UMA RS registration

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#63]
2016-12-29 10:21:37,862 ERROR [org.xdi.oxd.rs.protect.resteasy.ResourceRegistrar] Error status 406 Not Acceptable returned
org.jboss.resteasy.client.ClientResponseFailure: Error status 406 Not Acceptable returned
	at org.jboss.resteasy.client.core.BaseClientResponse.createResponseFailure(BaseClientResponse.java:523)
	at org.jboss.resteasy.client.core.BaseClientResponse.createResponseFailure(BaseClientResponse.java:514)
	at org.jboss.resteasy.client.core.BaseClientResponse.checkFailureStatus(BaseClientResponse.java:508)
	at org.jboss.resteasy.client.core.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:38)
	at org.jboss.resteasy.client.core.ClientInvoker.invoke(ClientInvoker.java:126)
	at org.jboss.resteasy.client.core.ClientProxy.invoke(ClientProxy.java:88)
	at com.sun.proxy.$Proxy46.addResourceSet(Unknown Source)
	at org.xdi.oxd.rs.protect.resteasy.ResourceRegistrar.register(ResourceRegistrar.java:89)
	at org.xdi.oxd.rs.protect.resteasy.ResourceRegistrar.register(ResourceRegistrar.java:50)
	at org.xdi.oxd.server.op.RsProtectOperation.execute(RsProtectOperation.java:58)
	at org.xdi.oxd.server.op.RsProtectOperation.execute(RsProtectOperation.java:31)
	at org.xdi.oxd.server.Processor.process(Processor.java:80)
	at org.xdi.oxd.server.Processor.process(Processor.java:55)
	at org.xdi.oxd.server.SocketProcessor.run(SocketProcessor.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2016-12-29 10:21:37,865 ERROR [org.xdi.oxd.server.Processor] Error status 406 Not Acceptable returned
org.jboss.resteasy.client.ClientResponseFailure: Error status 406 Not Acceptable returned
	at org.jboss.resteasy.client.core.BaseClientResponse.createResponseFailure(BaseClientResponse.java:523)
	at org.jboss.resteasy.client.core.BaseClientResponse.createResponseFailure(BaseClientResponse.java:514)
	at org.jboss.resteasy.client.core.BaseClientResponse.checkFailureStatus(BaseClientResponse.java:508)
	at org.jboss.resteasy.client.core.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:38)
	at org.jboss.resteasy.client.core.ClientInvoker.invoke(ClientInvoker.java:126)
	at org.jboss.resteasy.client.core.ClientProxy.invoke(ClientProxy.java:88)
	at com.sun.proxy.$Proxy46.addResourceSet(Unknown Source)
	at org.xdi.oxd.rs.protect.resteasy.ResourceRegistrar.register(ResourceRegistrar.java:89)
	at org.xdi.oxd.rs.protect.resteasy.ResourceRegistrar.register(ResourceRegistrar.java:50)
	at org.xdi.oxd.server.op.RsProtectOperation.execute(RsProtectOperation.java:58)
	at org.xdi.oxd.server.op.RsProtectOperation.execute(RsProtectOperation.java:31)
	at org.xdi.oxd.server.Processor.process(Processor.java:80)
	at org.xdi.oxd.server.Processor.process(Processor.java:55)
	at org.xdi.oxd.server.SocketProcessor.run(SocketProcessor.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yuriyz** [comment]
Fixed during moving to UMA 2.
